name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.1

      - name: Set environment variables
        run: |
          echo "GO111MODULE=on" >> $GITHUB_ENV
          echo "CGO_ENABLED=0" >> $GITHUB_ENV
          echo "GOPATH=${HOME}/go" >> $GITHUB_ENV

      - name: Install make (if not installed)
        run: |
          if ! command -v make &> /dev/null
          then
              sudo apt-get update && sudo apt-get install -y make
          fi

      - name: Unit Test
        run: make unit-tests
